/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorUI;
import Controlador.ManejoEstadistica;
import Controlador.Printer_Results;
import Modelo.Canton;
import Modelo.File_Reader;
import Modelo.Lock;
import Modelo.Provincia;
import java.io.IOException;
import java.util.HashMap;
import java.lang.String;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JRadioButton;

/**
 *
 * @author Silvia Araya J.
 */
public class Hilos_UI extends javax.swing.JFrame {

    /**
     * Creates new form Hilos_UI
     */
    DefaultListModel lista_model = new DefaultListModel();
   
    public Hilos_UI() {
        initComponents();
        lista.setModel(lista_model);
        
        ControladorUI controlador = new ControladorUI(this);
        setActionCommand(controlador);
    }
    private void setActionCommand(ControladorUI controlador){
        this.rbtnporCanton.addActionListener(controlador);
        this.rbtnGNacional.addActionListener(controlador);
        this.rbtnGProvincial.addActionListener(controlador);
        this.rbtnXML.addActionListener(controlador);
        this.rbtnTXT.addActionListener(controlador);
        this.rbtnJson.addActionListener(controlador);
        this.btnGuardar.addActionListener(controlador);
        this.btnSalir.addActionListener(controlador);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        rbtnXML = new javax.swing.JRadioButton();
        rbtnJson = new javax.swing.JRadioButton();
        rbtnTXT = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        rbtnGProvincial = new javax.swing.JRadioButton();
        rbtnporCanton = new javax.swing.JRadioButton();
        rbtnGNacional = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lista = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Engravers MT", 0, 15)); // NOI18N
        jLabel1.setText("Manejo estadistico de Padron electoral");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        jLabel2.setText("Seleccione el archivo de lugares");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 61, -1, -1));

        jLabel3.setText("Seleccione archivo de padron");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(396, 61, -1, -1));

        btnGuardar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnGuardar.setText("Guardar");
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, -1, -1));

        rbtnXML.setText("Guardar en XML");

        rbtnJson.setText("Guardar en JSon");

        rbtnTXT.setText("Guardar en TXT");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtnTXT)
                    .addComponent(rbtnJson)
                    .addComponent(rbtnXML))
                .addGap(17, 17, 17))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(rbtnTXT)
                .addGap(18, 18, 18)
                .addComponent(rbtnXML)
                .addGap(18, 18, 18)
                .addComponent(rbtnJson)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, 120));

        rbtnGProvincial.setText("Estadistica Genero por Provincias");

        rbtnporCanton.setText("Estadistica genero por Canton");

        rbtnGNacional.setText("Estadistica Nacional por Genero");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtnGNacional)
                    .addComponent(rbtnporCanton)
                    .addComponent(rbtnGProvincial))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(rbtnGNacional)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(rbtnGProvincial)
                .addGap(18, 18, 18)
                .addComponent(rbtnporCanton)
                .addGap(17, 17, 17))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        lista.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lista);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 340, 240));

        jLabel4.setText("Estadisticas");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, 70, -1));

        jLabel5.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 14)); // NOI18N
        jLabel5.setText("Seleccione el tipo de estadistica");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 200, -1));

        jLabel6.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 14)); // NOI18N
        jLabel6.setText("Seleccione el tipo de archivo a guardar");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 250, -1));

        btnSalir.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnSalir.setText("Salir");
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 430, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    /*------Metodo que agrega datos a la lista*/
    public void agregarDatos(ArrayList<String> values ){
        lista_model.clear();//se limpian datos de la lista
        for(int index=0;index<values.size();index++){
            lista_model.addElement(values.get(index));
        }
    }
    public static void main(String args[]) throws IOException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hilos_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hilos_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hilos_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hilos_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hilos_UI().setVisible(true);
            }
        });
    }

    public JRadioButton getRbtnJson() {
        return rbtnJson;
    }

    public void setRbtnJson(JRadioButton rbtnJson) {
        this.rbtnJson = rbtnJson;
    }

    public JRadioButton getRbtnTXT() {
        return rbtnTXT;
    }

    public void setRbtnTXT(JRadioButton rbtnTXT) {
        this.rbtnTXT = rbtnTXT;
    }

    public JRadioButton getRbtnXML() {
        return rbtnXML;
    }

    public void setRbtnXML(JRadioButton rbtnXML) {
        this.rbtnXML = rbtnXML;
    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lista;
    private javax.swing.JRadioButton rbtnGNacional;
    private javax.swing.JRadioButton rbtnGProvincial;
    private javax.swing.JRadioButton rbtnJson;
    private javax.swing.JRadioButton rbtnTXT;
    private javax.swing.JRadioButton rbtnXML;
    private javax.swing.JRadioButton rbtnporCanton;
    // End of variables declaration//GEN-END:variables
}
